"""create coins and snapshots

Revision ID: c28ba55613bb
Revises: 
Create Date: 2025-12-23 18:30:27.079905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28ba55613bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coingecko_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_coingecko_id'), 'coins', ['coingecko_id'], unique=True)
    op.create_table('coin_market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_market_snapshots_coin_id'), 'coin_market_snapshots', ['coin_id'], unique=False)
    op.create_index(op.f('ix_coin_market_snapshots_ts'), 'coin_market_snapshots', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_market_snapshots_ts'), table_name='coin_market_snapshots')
    op.drop_index(op.f('ix_coin_market_snapshots_coin_id'), table_name='coin_market_snapshots')
    op.drop_table('coin_market_snapshots')
    op.drop_index(op.f('ix_coins_coingecko_id'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
